root: true
env:
  es2021: true
  node: true
  browser: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: tsconfig(.*)?.json
  createDefaultProgram: true
plugins:
  - '@nx'
  - '@typescript-eslint'
  - eslint-comments
  - 'no-loops'
extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:eslint-comments/recommended
  - plugin:node/recommended
settings:
  jest:
    version: latest
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
      - '*.js'
      - '*.jsx'
    rules:
      '@nx/enforce-module-boundaries':
        - error
        - enforceBuildableLibDependency: true
          allow: []
          depConstraints:
            - sourceTag: '*'
              onlyDependOnLibsWithTags:
                - '*'
      # core
      node/no-missing-import: off
      node/no-unsupported-features/node-builtins:
        - error
        - version: '>=18'
      node/no-unsupported-features/es-syntax:
        - error
        - version: '>=18'
          ignores:
            - modules
            - dynamicImport
      no-console: 0
      consistent-return: 0
      quotes:
        - error
        - single
        - avoidEscape: true
          allowTemplateLiterals: true

      # variables
      no-unused-vars: 0

      # style
      object-curly-newline: 0
      lines-between-class-members: 0
      implicit-arrow-linebreak: 0
      arrow-body-style:
        - error
        - as-needed

      # import
      import/extensions: off
      import/named: off
      import/default: off
      import/namespace: off
      import/group-exports: off
      import/no-named-export: off
      import/no-named-as-default: off
      import/no-named-as-default-member: off
      import/no-unresolved:
        - 2
        - commonjs: true
          amd: true
          caseSensitive: true

      import/first: error
      import/no-amd: error
      import/no-duplicates: error
      import/no-self-import: error
      import/no-absolute-path: error
      import/no-named-default: error
      import/no-mutable-exports: error
      import/newline-after-import: error
      import/order:
        - error
        - groups:
            - builtin
            - external
            - internal
          newlines-between: never
          alphabetize:
            order: asc
            caseInsensitive: false

      # no-loops
      no-loops/no-loops: 2

      # comments
      eslint-comments/disable-enable-pair: off
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - plugin:@nx/typescript
    rules: {}
  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - plugin:@nx/javascript
    rules: {}
  - files:
      - '**/__mocks__'
      - '**/__factories__'
      - '**/__fixtures__'
      - '**/specs/**/*.ts'
      - '**/specs/**/*.tsx'
      - '**/tests/**/*.ts'
      - '**/tests/**/*.tsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - '!**/*.e2e.spec.ts'
      - 'jest.config.js'
      - 'jest.present.js'
    plugins:
      - jest
      - jest-dom
    extends:
      - plugin:jest/style
      - plugin:jest/recommended
      - plugin:jest-dom/recommended
      - plugin:jest-formatting/recommended
    env:
      jest/globals: true
    rules:
      node/no-unpublished-require: off
      node/no-unpublished-import: off
      node/no-extraneous-import: off
      import/no-extraneous-dependencies: off
  - files:
      - '**/cypress/*'
      - '**/e2e/*'
      - '**/*.e2e.spec.ts'
    plugins:
      - cypress
    extends:
      - plugin:cypress/recommended
    env:
      cypress/globals: true
    rules:
      jest/expect-expect: off
      jest/valid-expect: off
      node/no-unpublished-import: off
      node/no-extraneous-import: off
      import/no-extraneous-dependencies: off
